meta_product_name: "Les meilleures punchlines d'Oussama Ammar"
meta_title: "Quotes Oussama Ammar - Les meilleures punchlines d'Oussama Ammar"
meta_description: "Trouvez l'inspiration et le sourire dans ces citations d'Oussama Ammar, co-fondateur de la société d'investissement The Family."
meta_image: "cover.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
