meta_product_name: "Les meilleures punchlines d'Oussama Ammar"
meta_title: "Quotes Oussama Ammar - Les meilleures punchlines d'Oussama Ammar"
meta_description: "Find inspiration in these impactful punchlines from Oussama Ammar, co-founder of The Family."
meta_image: "cover.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
